### ISSUE TITLE
command line for running on YAGO and wiki

### ISSUE THREAD

**Issue by lihuiliullh** [Lee-zix/RE-GCN#15]
Can you share the command lines for running on YAGO and wiki?

I got such an error

FileNotFoundError: [Errno 2] No such file or directory: './data/YAGO/e-w-graph.txt'

**Comment by Lee-zix** [comment]
Static Graphs are only for ICEWS datasets. For YAGO and WIKI, static graphs are not generated and used. See Lines 17-19 in  Section Implementation Details ("We only report the results without the static graph constraint on WIKI, YAGO and GDELT because the static information is missing in these datasets.").
