### ISSUE TITLE
Filtered Result

### ISSUE THREAD

**Issue by Woolaowu** [Lee-zix/RE-GCN#2]
Hi,

very nice work!
I am just wondering why you didn't report filtered results in your paper, since filtered results are in most cases much fairer than raw results.

Could you please also post the filtered results of your model?
Thanks!

Zifeng

**Comment by Lee-zix** [comment]
Thanks for your attention. You can find your answer in section 5.1.2 of our paper. 

The widely adopted filtered setting in all our baselines is not suitable for the future fact prediction task addressed in this study. The reason is explained in terms of an example as follows: 
Given a test quadruple (Barack Obama, visit, ?, Jan. 25 2015) with the correct answer India. Assume there is a quadruple (Barack Obama, visit, Germany, Jan.18 2013) in the training set. The filtered setting used in the previous studies ignores time information and considers (Barack Obama, visit, Germany, Jan. 25 2015) to be valid because (Barack Obama, visit, Germany, Jan.18 2013) appears in the training set. It thus removes the quadruple from the corrupted ones. However, the fact (Barack Obama, visit, Germany) is temporally valid on Jan. 18 2013, instead of Jan. 25 2015. Therefore, to test the quadruple (Barack Obama, visit, ?, Jan. 25, 2015), (Barack Obama, visit, Germany, Jan.18, 2015) should not be removed. 
In this way, the filtered setting wrongly removes quite a lot of quadruples and thus leads to over-optimistic experimental performance in the future fact prediction task. 
The essential problem of the above traditional filtered setting is that it ignores the fourth element (i.e., time information) of the quadruple. Therefore, we ever tried an improved filtered setting, where the time information is also considered. However, because only a very small number of quadruples are removed, the experimental results are very close to those in the raw setting. Due to space limitation, we did not report the results in this paper.
